name: Android CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: cd VirtualApp && ./gradlew assembleRelease
    - name: ls
      run: ls -R VirtualApp/app/build/
    - name: Prepare artifact
      run: |
        mkdir -p ./artifact/package
        cp -rf $(find ./VirtualApp/app/build/ -type f -name "*.apk") ./artifact/package/
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: compiled
        path: ./artifact/package/
